#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES
#define TAILLE_BLOC         10
#define NB_BLOCS_LARGEUR    80
#define NB_BLOCS_HAUTEUR    60

#define LARGEUR_FENETRE     TAILLE_BLOC * NB_BLOCS_LARGEUR
#define HAUTEUR_FENETRE     TAILLE_BLOC * NB_BLOCS_HAUTEUR


enum {MORT, VIVANT};

#endif
